### ISSUE TITLE
HTML E-Book link issue

### ISSUE THREAD

**Issue by yohanhyunsungyi** [MHM5000/swift-cheat-sheet#5]
Hello,

Is there a specific reason for not inserting the arrow link from 8.Enum to 9-1.Protocol?

![image](https://user-images.githubusercontent.com/7391749/33503239-d35f1df8-d697-11e7-9717-24b53b875c3a.png)

![image](https://user-images.githubusercontent.com/7391749/33503210-bba44d78-d697-11e7-8614-f6d3707bf1ea.png)

**Comment by MHM5000** [comment]
Hi
The book uses a site generator called GitBook and is hosted on gitbook.com.

I checked it now and it's fixed.

Sorry for the delay in answering your question
